DESIGN_NAME: top_module
VERILOG_FILES: dir::src/*.v
CLOCK_PERIOD: 10
CLOCK_PORT: clk
PNR_SDC_FILE: dir::src/impl.sdc
SIGNOFF_SDC_FILE: dir::src/signoff.sdc

# PDN
PDN_CORE_RING: true
PDN_ENABLE_RAILS: true
PDN_HORIZONTAL_LAYER: met5
PDN_VERTICAL_LAYER: met4
PDN_HWIDTH: 3.1
PDN_VWIDTH: 3.1
PDN_HPITCH: 35
PDN_VPITCH: 35
PDN_HOFFSET: 10
PDN_VOFFSET: 10

# Pin Order
IO_PIN_ORDER_CFG: dir::pin_order.cfg

# Technology-Specific Configs
pdk::sky130*:
  FP_CORE_UTIL: 40
  CLOCK_PERIOD: 10.0
  DIE_AREA : [0,0,148,148]
  CORE_AREA : [10,10,138,138]
  FP_SIZING : "absolute"
  
  # Placement Variables
  PL_TARGET_DENSITY: 0.8
  PL_TIME_DRIVEN: true
  PL_ROUTABILITY_DRIVEN: true
  PL_RESIZER_TIMING_OPTIMIZATION: true
  GPL_CELL_PADDING: 4
  DPL_CELL_PADDING: 2

  scl::sky130_fd_sc_hs:
    CLOCK_PERIOD: 8
  scl::sky130_fd_sc_ls:
    MAX_FANOUT_CONSTRAINT: 5
